language: go

go:
  - 1.14.x
  - 1.15.x
  - master

addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev

matrix:
  fast_finish: true
  allow_failures:
    - go: master

env:
  - GO111MODULE=off
  - GO111MODULE=on

script:
  - go get -d -t -v ./...
  - go build -v `go list ./... | grep -v python`
  - go test `go list ./... | grep -v python`

notifications:
  email:
    recipients:
      - oreilly@ucdavis.edu
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://ccnlab.zulipchat.com/api/v1/external/travis?api_key=7lfyOrci6YROdaxqqdDvQnNMWWQBtNuW&stream=emergent&topic=travis
    on_success: change
    on_failure: always

