language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev

matrix:
  fast_finish: true
  allow_failures:
    - go: master

env:
  - GO111MODULE=off

script:
  - go get -d -t -v ./...
  - go build -v ./...
  - go test ./...

notifications:
  email:
    recipients:
      - oreilly@ucdavis.edu
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://ccnlab.zulipchat.com/api/v1/external/travis?api_key=7lfyOrci6YROdaxqqdDvQnNMWWQBtNuW&stream=emergent&topic=travis
    on_success: change
    on_failure: always

