Name = "ordmap"
Desc = ""
Version = "v0.5.2"
Type = "TypeLibrary"

[Build]
  Package = "."

[Colorgen]
  Source = "colors.xml"
  Output = "colorgen.go"
  Package = "main"
  Comment = ""

[Install]
  Package = "."

[Log]
  Target = "android"
  Keep = false
  All = "F"

[Release]
  VersionFile = "version.go"
  Package = "ordmap"
